# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='shared',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wished_by',
            field=models.ManyToManyField(related_name='wishes', to='first_app.User'),
        ),
        migrations.DeleteModel(
            name='Shared',
        ),
    ]
